#!/bin/bash

particle="photon"

# number of events to process
numberOfEvents=10000

# detector geometry
detectorGeometry="ILD_l4_v02"

# output directory in afs pool dir
outputDirectory="/afs/desy.de/group/flc/pool/eteremi"

# ilcsoft version
ilcsoftVersion="v01-19-03-pre02"

# scripts dir
scriptsDirectory=""

if [ -z "$PANDORA_CALIBRATION_JOBS_DIR" ]; then
  scriptsDirectory="$HOME/soft/PandoraCalibrationJobs/scripts/ddsim"
else
  scriptsDirectory="$PANDORA_CALIBRATION_JOBS_DIR/scripts/ddsim"
fi


# parse command line args
if [ "$#" -gt "0" ]; then
  particle=$1
fi

if [ "$#" -gt "1" ]; then
  ilcsoftVersion=$2
fi

if [ "$#" -gt "2" ]; then
  detectorGeometry=$3
fi

if [ "$#" -gt "3" ]; then
  numberOfEvents=$4
fi

if [ "$#" -gt "4" ]; then
  outputDirectory=$5
fi


# particle script
ddsimScript="ddsim-steering-${particle}.py"

# run directory
runDirectory=`mktemp --dir`

# output file
outputFile="ddsim-${particle}-s${ilcsoftVersion}-G${detectorGeometry}-calibration.slcio"

# log file
logFile="ddsim-${particle}-s${ilcsoftVersion}-G${detectorGeometry}.log"

# ==============
# Start of script

# create output directory
if [ ! -d "$outputDirectory" ]; then
  echo "Creating output directory: $outputDirectory"
  mkdir -p $outputDirectory

  if [ "$?" -neq "0" ]; then
    echo "Couldn't create output directory: $outputDirectory"
    exit 1
  fi
fi

# cd run directory and copy needed scripts for simulation
cd $runDirectory
cp $scriptsDirectory/* .

# ilcsoft stuff
unset MARLIN_DLL
source /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/${ilcsoftVersion}/init_ilcsoft.sh

echo "Running zith ilcsoft version ${ilcsoftVersion}"
echo "Running ddsim with :"
echo "   - n evts = ${numberOfEvents}"
echo "   - detectorGeometry = ${detectorGeometry}"
echo "   - ddsimScript = ${ddsimScript}"
echo "   - outputFile = ${outputFile}"


echo ""
echo "============================="
echo "======= RUNNING DDSIM ======="
echo "============================="

# run simulation
ddsim \
   --outputFile=./${outputFile} \
   --compactFile=${lcgeo_DIR}/ILD/compact/${detectorGeometry}/${detectorGeometry}.xml \
   --steeringFile=./${ddsimScript} \
   --numberOfEvents=${numberOfEvents} \
   > ${logFile}

echo ""
echo "============================="
echo "=======  DDSIM  DONE  ======="
echo "============================="

echo ""
echo "============================="
echo "Converting dd4hep file to gear for further use ..."
echo "============================="

convertToGear default ${lcgeo_DIR}/ILD/compact/${detectorGeometry}/${detectorGeometry}.xml gear_${detectorGeometry}_dd4hep.xml

# copy output files to output directory
cp ${outputFile} ${outputDirectory}
cp ${logFile} ${outputDirectory}
cp gear_${detectorGeometry}_dd4hep.xml ${outputDirectory}

# clean up run directory
rm -rf ${runDirectory}

#
