#!/bin/bash
#
# @author : R.Ete, DESY
#
# Script to extract the calibration constants from the
# Calibration .txt file written by the SimCaloHitEnergyDistribution binary
# from PandoraAnalysis package
#
# These calibration constants are the first step in the full calibration procedure.
#

# Usage
if [ "$#" -ne "2" ]; then
  echo "Usage: extract-calibration-constants calibrationFile outputMode"
  echo ""
  echo "  calibrationFile       txt file output from SimCaloHitEnergyDistribution"
  echo "                        binary from PandoraAnalysis package"
  echo "  outputMode            marlin|echo"
  echo "                        'marlin' to print calib constants into Marlin cmd line format"
  echo "                        'echo' print into stdout"
  exit 1
fi

# (ugly) functions to extract variables from the txt file
getHcalBarrelMip () {
  mip=`sed '7q;d' $1 | awk '{print $6}'`
  ret=$?

  if [ "$ret" -ne "0" ]; then
    echo "Couldn't get the hcal barrel mip !"
    exit $ret
  fi

  echo "$mip"
}

getHcalEndcapMip () {
  mip=`sed '8q;d' $1 | awk '{print $6}'`
  ret=$?

  if [ "$ret" -ne "0" ]; then
    echo "Couldn't get the hcal endcap mip !"
    exit $ret
  fi

  echo "$mip"
}

getHcalRingMip () {
  mip=`sed '9q;d' $1 | awk '{print $6}'`
  ret=$?

  if [ "$ret" -ne "0" ]; then
    echo "Couldn't get the hcal ring mip !"
    exit $ret
  fi

  echo "$mip"
}

getEcalMip () {
  mip=`sed '10q;d' $1 | awk '{print $5}'`
  ret=$?

  if [ "$ret" -ne "0" ]; then
    echo "Couldn't get the ecal mip !"
    exit $ret
  fi

  echo "$mip"
}

calibrationFile="$1"

if [ ! -f $calibrationFile ]; then
  echo "Calibration file '$calibrationFile' doesn't exists"
  exit 1
fi

# extract constants once
hcalBarrelMip=`getHcalBarrelMip $calibrationFile`
hcalEndcapMip=`getHcalEndcapMip $calibrationFile`
hcalRingMip=`getHcalRingMip $calibrationFile`
ecalMip=`getEcalMip $calibrationFile`


# output constants
if [ "$#" -gt "1" ]; then
  case "$2" in
  "marlin") # print the four calibration constants in a readable way for Marlin
    echo "--MyEcalBarrelDigi.calibration_mip=$ecalMip --MyEcalEndcapDigi.calibration_mip=$ecalMip --MyEcalRingDigi.calibration_mip=$ecalMip --MyHcalBarrelDigi.calibration_mip=$hcalBarrelMip --MyHcalEndcapDigi.calibration_mip=$hcalEndcapMip --MyHcalRingDigi.calibration_mip=$hcalRingMip"
    exit 0
    ;;
  "echo")
    echo "hcal barrel mip : $hcalBarrelMip"
    echo "hcal endcap mip : $hcalEndcapMip"
    echo "hcal ring mip : $hcalRingMip"
    echo "ecal mip : $ecalMip"
    exit 0
    ;;
  *)
    echo "Wrong output mode. Please specify one of these : marlin|echo"
    exit 1
    ;;
  esac
fi



#
