#!/bin/bash

ilcsoft=$1
ildconfig=$2
detector=$3
script=$LCCALIBRATION_DIR/nafhh/calibration/run-soft-comp-root-producer

# submit software compensation jobs: root file producer only
for energy in 10 20 30 40 50 60 70 80 90
do
  qsub ${script} ${ilcsoft} ${ildconfig} ${detector} ${energy}
done