#!/bin/bash
#
#(make sure the right shell will be used)
#$ -S /bin/bash
#
#execute the job from the current directory and not relative to your home directory
#$ -cwd

# sld6 for bird on NAF2
#$ -l arch=amd64
#$ -l os=sld6

#$ -l h_rt=23:59:00
#$ -l h_vmem=4G

#set the email address
##$ -M <user>@desy.de
#
#send email when job aborts or when job ends
##$ -m ae

echo "############################################################################"
echo "                             System information"
echo "                             =================="

echo "Host:"
hostname -f

echo "CPU(s):"
cat /proc/cpuinfo | grep "model name" | cut -b 14-

echo "RAM:"
cat /proc/meminfo | grep "MemTotal" | cut -b 10-

echo "Swap:"
cat /proc/meminfo | grep "SwapTotal" | cut -b 11-

echo "############################################################################"
echo "Group:      ${GROUP}"

echo "Hosttype:   ${HOSTTYPE}"

echo "JobID:      ${JOB_ID}"

echo "JobName:    ${JOB_NAME}"

echo "Job_Script: ${JOB_SCRIPT}"

echo "User:       ${LOGNAME}"

echo "Queue:      ${QUEUE}"

echo "Shell:      ${SHELL}"

echo "TMP:        ${TMP}"

echo "TMPDIR:     ${TMPDIR}"

echo "User:       ${USER}"

echo "Working_DIR:${PWD}"

echo "############################################################################"
echo
echo "############################################################################"
echo


ilcsoft=$1
detector=$2
particle=$3
energy=$4

source /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/${ilcsoft}/init_ilcsoft.sh

outputDirectory=/nfs/dust/ilc/group/ild/calibration/ddsim
outputFile=${outputDirectory}/ddsim-s${ilcsoft}-G${detector}-P${particle}-E${energy}-ILDCalibration.slcio
compactFile=$lcgeo_DIR/ILD/compact/${detector}/${detector}.xml
steeringFile=./steering/ddsim-steering-template.py

# Make sure the output directory exists
mkdir -p ${outputDirectory}

ddsim --compactFile ${compactFile} \
  --steeringFile ${steeringFile} \
  --outputFile ${outputFile} \
  --numberOfEvents 20000 \
  --physicsList QGSP_BERT \
  --enableGun \
  --gun.particle ${particle} \
  --gun.energy ${energy}000 \
  --gun.distribution uniform \
  --gun.phiMin 0 \
  --gun.phiMax 3.1415 \
  --gun.thetaMin 0 \
  --gun.thetaMax 3.1415
