#!/bin/bash

ilcsoft=$1
detector=$2
script=$LCCALIBRATION_DIR/nafhh/ddsim/run-single-particle

echo "Sending jobs using script ${script}"

# submit photon sim
echo "== Sending ddsim photon jobs =="
for split in 0 1 2 3 4 5 6 7 8 9
do
  qsub ${script} ${ilcsoft} ${detector} gamma 10 ${split}
done

# submit muon sim
echo "== Sending ddsim muon jobs =="
for split in 0 1 2 3 4 5 6 7 8 9
do
  qsub ${script} ${ilcsoft} ${detector} mu- 10 ${split}
done

# submit kaon0L sim
echo "== Sending ddsim kaon0L jobs =="
for energy in 10 20 30 40 50 60 70 80 90
do
  for split in 0 1 2 3 4 5 6 7 8 9
  do
    qsub ${script} ${ilcsoft} ${detector} kaon0L ${energy} ${split}
  done
done
